### ISSUE TITLE
parsing "^\_ReSharper\.PrMultimediaArchive$" - Unrecognized escape sequence \_.

### ISSUE THREAD

**Issue by manjunathmaskicision** [snyk/snyk-visual-studio-plugin#159]
![image](https://user-images.githubusercontent.com/97578713/169480008-028e7995-8ca2-4b4a-8c61-1e06d0b21b2f.png)

**Comment by manjunathmaskicision** [comment]
2022-05-25 10:30:04.759 [25248] EROR [290] SnykCodeService           Failed to obtain Snyk Code error message
System.ArgumentException: parsing "^\_ReSharper\.PrMultimediaArchive$" - Unrecognized escape sequence \_.
   at System.Text.RegularExpressions.RegexParser.ScanCharEscape()
   at System.Text.RegularExpressions.RegexParser.ScanBasicBackslash()
   at System.Text.RegularExpressions.RegexParser.ScanBackslash()
   at System.Text.RegularExpressions.RegexParser.ScanRegex()
   at System.Text.RegularExpressions.RegexParser.Parse(String re, RegexOptions op)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options)
   at MAB.DotIgnore.IgnoreRule..ctor(String pattern, MatchFlags flags, Nullable`1 lineNumber)
   at MAB.DotIgnore.IgnoreList.<>c__DisplayClass20_0.<AddRules>b__0(RuleLine line)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at MAB.DotIgnore.IgnoreList.AddRules(IEnumerable`1 rules, MatchFlags flags, Boolean loadedFromFile)
   at MAB.DotIgnore.IgnoreList..ctor(String ignoreFilePath, MatchFlags flags)
   at Snyk.Code.Library.Service.DcIgnoreService.FilterFilesByFileIgnoreList(String ignoreFilePath, IEnumerable`1 filePaths)
   at Snyk.Code.Library.Service.DcIgnoreService.FilterFilesByIgnoreFile(String folderPath, String ignoreFileName, IEnumerable`1 filePaths, CancellationToken cancellationToken)
   at Snyk.Code.Library.Service.DcIgnoreService.FilterFiles(String folderPath, IEnumerable`1 filePaths, CancellationToken cancellationToken)
   at Snyk.Code.Library.Service.SnykCodeService.<GetFilteredFilesAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Snyk.Code.Library.Service.SnykCodeService.<NewScanAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Snyk.Code.Library.Service.SnykCodeService.<ScanAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by manjunathmaskicision** [comment]
PrMultimediaArchive - Is our folder in the solution.

**Comment by aldanchenko** [comment]
Hi @manjunathmaskicision 👋,

Is this issue still relevant? If yes did you check `.dcignore` file rules? Could you try to delete all rules from `.dcignore` and run a scan again, please?

Best regards,
Alex

**Comment by michelkaporin** [comment]
Hi, since GitHub issues are not officially monitored by Snyk support, we will be disabling "Issues" tab on this repository very soon. 

Please raise the current issue directly by [contacting Snyk Support on the web](http://support.snyk.io) or emailing us at support@snyk.io.
