### ISSUE TITLE
VS2022 Error: The specified executable is not a valid application for this OS platform

### ISSUE THREAD

**Issue by tinonetic** [snyk/snyk-visual-studio-plugin#197]
Hi,

I am trying to run Snyk on VS2022 and I am getting the error: "The specified executable is not a valid application for this OS platform"

**Environment details:**

VS2022 17.2.6
Windows 10 21H2
Snyk 1.1.24

**Logs**

> 2022-07-20 12:40:03.894 [07052] INFO [01] SnykService               Initialize Snyk services
2022-07-20 12:40:03.921 [07052] INFO [01] SnykTasksService          SnykTasksService initialized
2022-07-20 12:40:03.924 [07052] INFO [01] SnykSolutionService       Enter InitializeSolutionEvents method
2022-07-20 12:40:03.924 [07052] INFO [01] SnykSolutionService       Leave InitializeSolutionEvents method
2022-07-20 12:40:03.924 [07052] INFO [01] SnykService               Leave SnykService.InitializeAsync
2022-07-20 12:40:03.924 [07052] INFO [01] SnykVSPackage             Get SnykService as ServiceProvider.
2022-07-20 12:40:03.924 [07052] INFO [01] SnykVSPackage             Start InitializeGeneralOptionsAsync.
2022-07-20 12:40:03.926 [07052] INFO [01] SnykVSPackage             Call GetDialogPage to create. await JoinableTaskFactory.SwitchToMainThreadAsync().
2022-07-20 12:40:03.926 [07052] INFO [01] SnykVSPackage             GeneralOptionsDialogPage not created yet. Call GetDialogPage to create.
2022-07-20 12:40:03.938 [07052] INFO [01] SnykVSPackage             Call generalOptionsDialogPage.Initialize()
2022-07-20 12:40:03.942 [07052] INFO [01] SnykService               Initialize Analytics Service...
2022-07-20 12:40:03.950 [07052] INFO [01] SnykService               analytics enabled = true, endpoint = https://snyk.io/api/user/me
2022-07-20 12:40:03.959 [07052] INFO [01] SnykAnalyticsService      Initializing analytics service instance
2022-07-20 12:40:03.963 [07052] INFO [01] SnykAnalyticsService      Loading Iteratively
2022-07-20 12:40:04.098 [07052] INFO [01] SnykAnalyticsService      Analytics set to enabled
2022-07-20 12:40:04.098 [07052] INFO [01] SnykAnalyticsService      Analytics service instance initialized
2022-07-20 12:40:04.098 [07052] INFO [01] SnykService               Analytics service initialized
2022-07-20 12:40:04.102 [07052] INFO [01] SnykAnalyticsService      Identifying user
2022-07-20 12:40:05.773 [07052] INFO [01] SnykAnalyticsService      Identifying segment client. User-Id = 5158cd16-7515-496b-acdf-06fc0917e2ee, Anonymous Id = 3fc722db-aa4f-42c7-81f9-a7b5fe7ff867, Vs Version: Visual Studio 2022
2022-07-20 12:40:05.781 [07052] INFO [01] SnykAnalyticsService      Analytics identification completed
2022-07-20 12:40:05.784 [07052] INFO [01] SnykVSPackage             Initialize Commands()
2022-07-20 12:40:05.791 [07052] INFO [01] SnykVSPackage             Initializing tool window
2022-07-20 12:40:05.793 [07052] INFO [01] SnykVSPackage             ToolWindow is not initialized. Call await JoinableTaskFactory.SwitchToMainThreadAsync().
2022-07-20 12:40:05.793 [07052] INFO [01] SnykVSPackage             Call FindToolWindow().
2022-07-20 12:40:05.955 [07052] INFO [01] SnykVSPackage             Check ToolWindow is not null Snyk.VisualStudio.Extension.Shared.UI.Toolwindow.SnykToolWindow.
2022-07-20 12:40:05.955 [07052] INFO [01] SnykVSPackage             Initialize ToolWindow.Content. Call await JoinableTaskFactory.SwitchToMainThreadAsync().
2022-07-20 12:40:05.955 [07052] INFO [01] SnykVSPackage             Call ToolWindow.Content.
2022-07-20 12:40:05.955 [07052] INFO [01] SnykVSPackage             Leave InitializeToolWindowControlAsync() method
2022-07-20 12:40:05.958 [07052] INFO [01] SnykVSPackage             Before call toolWindowControl.InitializeEventListeners() method.
2022-07-20 12:40:05.959 [07052] INFO [01] SnykToolWindowControl     Enter InitializeEventListenersAsync() method.
2022-07-20 12:40:05.959 [07052] INFO [01] SnykToolWindowControl     Initialize Solultion Event Listeners
2022-07-20 12:40:05.959 [07052] INFO [01] SnykToolWindowControl     Initialize CLI Event Listeners
2022-07-20 12:40:05.960 [07052] INFO [01] SnykToolWindowControl     Initialize Download Event Listeners
2022-07-20 12:40:05.961 [07052] INFO [01] SnykToolWindowControl     Leave InitializeEventListenersAsync() method.
2022-07-20 12:40:20.500 [07052] INFO [01] SnykTasksService          Enter Download method
2022-07-20 12:40:20.500 [07052] INFO [01] SnykTasksService          Start run task
2022-07-20 12:40:20.507 [07052] INFO [32] SnykCliDownloader         Enter GetLatestReleaseInfo method
2022-07-20 12:40:20.508 [07052] INFO [32] SnykCliDownloader         Get latest CLI release info
2022-07-20 12:40:22.020 [07052] INFO [01] SnykCodeClient            Create http client with with url https://deeproxy.snyk.io/.
2022-07-20 12:40:32.618 [07052] INFO [01] SnykTasksService          Enter Scan method
2022-07-20 12:40:32.930 [07052] INFO [01] SnykTasksService          Start scan task
2022-07-20 12:40:35.607 [07052] INFO [31] SnykSolutionService       Solution folder from is C:\Source\MyApplicationFolder\API
2022-07-20 12:40:35.607 [07052] INFO [31] SnykSolutionService       Result solution folder from is C:\Source\MyApplicationFolder\API
2022-07-20 12:40:35.615 [07052] INFO [31] OssService                Custom Endpoint is null
2022-07-20 12:40:35.615 [07052] INFO [31] OssService                Organization null
2022-07-20 12:40:35.616 [07052] INFO [31] OssService                Ignore Unknown CA is false
2022-07-20 12:40:35.622 [07052] INFO [31] SnykUserStorageSettingsService Enter GetAdditionalOptions method
2022-07-20 12:40:35.654 [07052] INFO [23] SnykSolutionService       Solution folder from is C:\Source\MyApplicationFolder\API
2022-07-20 12:40:35.654 [07052] INFO [23] SnykSolutionService       Result solution folder from is C:\Source\MyApplicationFolder\API
2022-07-20 12:40:35.655 [07052] INFO [23] OssService                Additional Options is 
2022-07-20 12:40:35.660 [07052] INFO [23] SnykUserStorageSettingsService Enter GetIsAllProjectsEnabled method
2022-07-20 12:40:35.680 [07052] INFO [36] SnykSolutionService       Solution folder from is C:\Source\MyApplicationFolder\API
2022-07-20 12:40:35.680 [07052] INFO [36] SnykSolutionService       Result solution folder from is C:\Source\MyApplicationFolder\API
2022-07-20 12:40:35.681 [07052] INFO [36] OssService                Is Scan All Projects is true
2022-07-20 12:40:35.681 [07052] INFO [36] OssService                Solution path is C:\Source\MyApplicationFolder\API
2022-07-20 12:40:35.681 [07052] INFO [36] OssService                Start scan
2022-07-20 12:40:35.685 [07052] INFO [36] SnykCli                   Path to scan C:\Source\MyApplicationFolder\API
2022-07-20 12:40:35.686 [07052] INFO [36] SnykCli                   CLI path is C:\Users\MyUser\AppData\Local\Snyk\snyk-win.exe
2022-07-20 12:40:35.690 [07052] INFO [36] SnykCli                   Enter BuildArguments method
2022-07-20 12:40:35.690 [07052] INFO [36] SnykUserStorageSettingsService Enter GetAdditionalOptions method
2022-07-20 12:40:35.735 [07052] INFO [08] SnykSolutionService       Solution folder from is C:\Source\MyApplicationFolder\API
2022-07-20 12:40:35.735 [07052] INFO [08] SnykSolutionService       Result solution folder from is C:\Source\MyApplicationFolder\API
2022-07-20 12:40:35.736 [07052] INFO [08] SnykUserStorageSettingsService Enter GetIsAllProjectsEnabled method
2022-07-20 12:40:35.757 [07052] INFO [27] SnykSolutionService       Solution folder from is C:\Source\MyApplicationFolder\API
2022-07-20 12:40:35.757 [07052] INFO [27] SnykSolutionService       Result solution folder from is C:\Source\MyApplicationFolder\API
2022-07-20 12:40:35.758 [07052] INFO [27] SnykCli                   Result CLI options --json test --all-projects
2022-07-20 12:40:35.759 [07052] INFO [27] SnykCli                   Leave BuildArguments method
2022-07-20 12:40:35.760 [07052] INFO [27] SnykCli                   Token added from Options
2022-07-20 12:40:35.762 [07052] INFO [27] SnykCli                   Start run console process
2022-07-20 12:40:36.285 [07052] EROR [27] SnykConsoleRunner         Cli running process error.
System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Snyk.VisualStudio.Extension.Shared.CLI.SnykConsoleRunner.Execute()
2022-07-20 12:40:36.537 [07052] INFO [27] SnykCli                   Start convert console string result to CliResult and return value
2022-07-20 12:40:36.540 [07052] INFO [27] OssService                Scan finished. Is successful: false
2022-07-20 12:40:36.540 [07052] EROR [27] SnykTasksService          Oss scan exception
Snyk.VisualStudio.Extension.Shared.Service.OssScanException: Exception of type 'Snyk.VisualStudio.Extension.Shared.Service.OssScanException' was thrown.
   at Snyk.VisualStudio.Extension.Shared.Service.OssService.<ScanAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Snyk.VisualStudio.Extension.Shared.Service.SnykTasksService.<RunOssScanAsync>d__74.MoveNext()
2022-07-20 12:40:41.900 [07052] INFO [01] SnykTasksService          Enter Download method
2022-07-20 12:40:41.900 [07052] INFO [01] SnykTasksService          Start run task
2022-07-20 12:40:41.901 [07052] INFO [30] SnykCliDownloader         Enter GetLatestReleaseInfo method
2022-07-20 12:40:41.901 [07052] INFO [30] SnykCliDownloader         Get latest CLI release info

Hoping you can assist.

Thanks for the great tool!

**Comment by asaf92** [comment]
Hi @tinonetic !
The release had nothing to do with it. Did this error prevent you from running scans previously and now it doesn't?

**Comment by michelkaporin** [comment]
Hi, since GitHub issues are not officially monitored by Snyk support, we will be disabling "Issues" tab on this repository very soon. 

Please raise the current issue directly by [contacting Snyk Support on the web](http://support.snyk.io) or emailing us at support@snyk.io.
