### ISSUE TITLE
Authentication process to Snyk does not populate the TOKEN field.

### ISSUE THREAD

**Issue by jdemaree** [snyk/snyk-visual-studio-plugin#98]
Using the most recent extension the authentication process goes all the way through but then fails to populate the token field.
VS Pro 2022 (64-bit) v 17.1.0 

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/49085407/156469019-0049478c-b46c-48a2-a17b-5ced57a0552f.png)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/49085407/156469039-4e406c6d-2379-4be9-858f-5d02d7d7f9c9.png)

![MicrosoftTeams-image](https://user-images.githubusercontent.com/49085407/156468854-08ba2f69-117b-4554-8a06-aebd9ace7fab.png)

After populating the token, with the user's API token from the portal VS Pro throws a self-signed certificate error.

**Comment by aldanchenko** [comment]
Hi @jdemaree!

Thank you for information. I'm working on it. Will let you know when we publish new version with a fix.

**Comment by mwazzangrg** [comment]
Is there any update on this guys?

**Comment by aldanchenko** [comment]
Hi @mwazzangrg,

Thanks for your input! Could you share steps to reproduce and logs with us? This will help us resolve this issue faster.

Best regards,
Alex

**Comment by mwazzangrg** [comment]
Hi Alex, it's all mentioned above in the original ticket. I'm using VS2022

**Comment by aldanchenko** [comment]
Hi @mwazzangrg, thanks! I see. Maybe you could share log file?

https://github.com/snyk/snyk-visual-studio-plugin#how-to-find-the-log-files

**Comment by mwazzangrg** [comment]
Thanks I've managed to copy and paste the token manually. Now when I run a scan it errors, here is my log file
[snyk-extension.log](https://github.com/snyk/snyk-visual-studio-plugin/files/8770566/snyk-extension.log)
.

**Comment by mwazzangrg** [comment]
Hi @aldanchenko not sure you saw my response. The plugin is still failing. See logs below:


`2022-06-10 10:51:39.762 [35820] INFO [88] SnykCli                   Result CLI options --json test --org=GR --all-projects
2022-06-10 10:51:39.762 [35820] INFO [88] SnykCli                   Leave BuildArguments method
2022-06-10 10:51:39.762 [35820] INFO [88] SnykCli                   Token added from Options
2022-06-10 10:51:39.763 [35820] INFO [88] SnykCli                   Start run console process
2022-06-10 10:51:44.721 [35820] INFO [88] SnykCli                   Start convert console string result to CliResult and return value
2022-06-10 10:51:44.721 [35820] INFO [88] OssService                Scan finished. Is successful: false
2022-06-10 10:51:44.721 [35820] EROR [88] SnykTasksService          Oss scan exception
Snyk.VisualStudio.Extension.Shared.Service.OssScanException: Exception of type 'Snyk.VisualStudio.Extension.Shared.Service.OssScanException' was thrown.
   at Snyk.VisualStudio.Extension.Shared.Service.OssService.<ScanAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Snyk.VisualStudio.Extension.Shared.Service.SnykTasksService.<RunOssScanAsync>d__74.MoveNext()
2022-06-10 10:51:44.724 [35820] EROR [88] SnykTasksService          Error on oss scan
System.NullReferenceException: Object reference not set to an instance of an object.
   at Snyk.VisualStudio.Extension.Shared.UI.Notifications.VsStatusBarNotificationService.OnOssScanError(Object sender, SnykCliScanEventArgs eventArgs)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Snyk.VisualStudio.Extension.Shared.Service.SnykTasksService.<RunOssScanAsync>d__74.MoveNext()`

**Comment by aldanchenko** [comment]
Hi @mwazzangrg 👋

Could you, please, update Visual Studio to the latest version (for me its 17.2.3 right now) and update Snyk extension (current version is 1.1.21)? And after this could, please, try to authenticate again and if error still exists, share logs here?

Thank you!

Best regards,
Alex

**Comment by jtreher** [comment]
https://medium.com/@JockDaRock/disabling-ipv6-on-network-adapter-windows-10-5fad010bca75 Turned out to be my issue. I had a different client IP being used from the CLI vs the browser.

**Comment by asaf92** [comment]
Hi @jtreher !
Thanks for all the details. It seems that there's an authentication issue related to IPv6 with the `snyk auth` command.
Other than disabling IPv6, does setting the token in the plugin settings solve the problem?

**Comment by jtreher** [comment]
@asaf92 Manually entering the token did not work. The only thing that worked was disabling IPv6.

**Comment by michelkaporin** [comment]
Hi, since GitHub issues are not officially monitored by Snyk support, we will be disabling "Issues" tab on this repository very soon. 

Please raise the current issue directly by [contacting Snyk Support on the web](http://support.snyk.io) or emailing us at support@snyk.io.
